<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MyDOC</title>

<link type="text/css" rel="stylesheet" href="assets/css/bootstrap.css" />

<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.sidebar-nav {
		padding: 9px 0;
	}
</style>

<link type="text/css" rel="stylesheet" href="assets/css/bootstrap-responsive.min.css" />

<?php if (($webfont = Config::get('mydoc.webfont', false)) !== false): ?>
<link href="http://fonts.googleapis.com/css?family=<?php echo urlencode($webfont); ?>" rel="stylesheet" type="text/css">
<style>
body { font-family: "<?php echo $webfont; ?>", sans-serif; }
</style>
<?php endif; ?>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
	$("._extra").tooltip({
		"html" : true,
		"title" : "PK : Primary key<br />UI : Unique<br />AI : Auto increment<br />FK : Foreign key"
	});
	$("._foreign_key").tooltip({
	});
});
</script>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="index.html">MyDOC</a>
			<ul class="nav">
				<li class="active"><a href="tables.html">Tables</a></li>
				<li><a href="indexes.html">Indexes</a></li>
				<li><a href="triggers.html">Triggers</a></li>
			</ul>
		</div>
	</div>
</div><!--/navbar-->

<div class="container">

	<h1><?php echo $table_name; ?></h1>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th style="width:10%;">Name</th>
				<th style="width:10%;">Type</th>
				<th style="width:5%;">Len</th>
				<th style="width:5%;">Null</th>
				<th style="width:5%;">Def</th>
				<th style="width:15%;">Extra <span class="_extra"><i class="icon-question-sign"></i></span></th>
				<th style="width:50%;">Comment</th>
			</tr>
		</thead>
		<tbody>
<?php foreach ($columns as $column_name => $column_data): ?>
			<tr>
	<?php if(empty($column_data['_foreign_key']['referenced_table_name'])): ?>
				<td><?php echo $column_name; ?></td>
	<?php else: ?>
				<td>
					<a href="table_<?php echo $column_data['_foreign_key']['referenced_table_name']; ?>.html"><?php echo $column_name; ?></a>
					<span class="_foreign_key" title="<?php echo $column_data['_foreign_key']['referenced_table_name'].'.'.$column_data['_foreign_key']['referenced_column_name']; ?>" ><i class="icon-question-sign"></i>
				</td>
	<?php endif; ?>
				<td><?php echo $column_data['data_type']; ?></td>
				<td><?php echo $column_data['_length']; ?></td>
				<td><?php echo empty($column_data['null']) ? 'No' : 'Yes'; ?></td>
				<td><?php echo $column_data['default']; ?></td>
				<td><span class="label label-info"><?php echo implode('</span> <span class="label label-info">', $column_data['_extras']); ?></span></td>
				<td><?php echo $column_data['comment']; ?></td>
			</tr>
<?php endforeach; ?>
		</tbody>
	</table><!--/.table-->

	<hr />

	<h2>Indexes</h2>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th style="width:20%;">Name</th>
				<th style="width:10%;">Unique</th>
				<th style="width:20%;">Column</th>
				<th style="width:50%;">Comment</th>
			</tr>
		</thead>
		<tbody>
<?php foreach ($infos['indexes'] as $index_name => $columns): ?>
	<?php foreach ($columns as $column_name => $column_info): ?>
			<tr>
				<td><?php echo $index_name; ?></td>
				<td><?php echo empty($column_info['non_unique']) ? 'Yes' : 'No'; ?></td>
				<td><?php echo $column_name; ?></td>
				<td><?php echo $column_info['comment']; ?></td>
			</tr>
	<?php endforeach; ?>
<?php endforeach; ?>
		</tbody>
	</table><!--/.table-->

	<hr />

	<h2>Triggers</h2>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th style="width:15%;">Name</th>
				<th style="width:15%;">Timing</th>
				<th style="width:15%;">Definer</th>
				<th style="width:55%;">Statement</th>
			</tr>
		</thead>
		<tbody>
<?php foreach ($infos['triggers'] as $trigger): ?>
		<tr>
			<td><?php echo $trigger['trigger_name']; ?></td>
			<td><?php echo $trigger['action_timing']; ?> <?php echo $trigger['event_manipulation']; ?></td>
			<td><?php echo $trigger['definer']; ?></td>
			<td><pre><?php echo $trigger['action_statement']; ?></pre></td>
		</tr>
<?php endforeach; ?>
		</tbody>
	</table><!--/.table-->

	<hr />

	<footer>
		<p class="pull-left">
			<?php echo Html::anchor('https://github.com/mp-php/', 'MyDOC'); ?>
			 developed by <?php echo Html::anchor('http://madroom-project.blogspot.jp/', 'madroom project'); ?>
		</p>
		<p class="pull-right">
			Generated by <?php echo Html::anchor('http://fuelphp.com/', 'FuelPHP'); ?> <?php echo Fuel::VERSION; ?>
			 and using <?php echo Html::anchor('http://twitter.github.com/bootstrap/', 'Twitter Bootstrap'); ?>
		</p>
	</footer>

</div><!--/.container-->

</body>
</html>
