<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>MyDOC</title>

<link type="text/css" rel="stylesheet" href="assets/css/bootstrap.css" />

<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.sidebar-nav {
		padding: 9px 0;
	}
</style>

<link type="text/css" rel="stylesheet" href="assets/css/bootstrap-responsive.min.css" />

<?php if (($webfont = Config::get('mydoc.webfont', false)) !== false): ?>
<link href="http://fonts.googleapis.com/css?family=<?php echo urlencode($webfont); ?>" rel="stylesheet" type="text/css">
<style>
body { font-family: "<?php echo $webfont; ?>", sans-serif; }
</style>
<?php endif; ?>

</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="index.html">MyDOC</a>
			<ul class="nav">
				<li class="active"><a href="tables.html">Tables</a></li>
				<li><a href="indexes.html">Indexes</a></li>
				<li><a href="triggers.html">Triggers</a></li>
			</ul>
		</div>
	</div>
</div><!--/navbar-->

<div class="container">

	<h1>Tables</h1>
<?php foreach ($tables as $table_name): ?>
	<a href="table_<?php echo $table_name; ?>.html"><?php echo $table_name; ?></a><br />
<?php endforeach; ?>

	<hr />

	<footer>
		<p class="pull-left">
			<?php echo Html::anchor('https://github.com/mp-php/', 'MyDOC'); ?>
			 developed by <?php echo Html::anchor('http://madroom-project.blogspot.jp/', 'madroom project'); ?>
		</p>
		<p class="pull-right">
			Generated by <?php echo Html::anchor('http://fuelphp.com/', 'FuelPHP'); ?> <?php echo Fuel::VERSION; ?>
			 and using <?php echo Html::anchor('http://twitter.github.com/bootstrap/', 'Twitter Bootstrap'); ?>
		</p>
	</footer>

</div><!--/.container-->

</body>
</html>
